### ISSUE TITLE
Caused error that "Failed to check JDK distribution: 'jpackage' is missing" 

### ISSUE THREAD

**Issue by kaleidot725** [kaleidot725/AdbPad#106]
## Problem

Using jbr on macos and get error "Failed to check JDK distribution: 'jpackage' is missing"

**Comment by crowforkotlin** [comment]
Alas, I also encountered this problem

**Comment by crowforkotlin** [comment]
This problem is because jewel needs to use the jbr runtime, but jpackage and jmod do not exist in the jbr on the Mac system, which leads to the failure of packaging on the Mac. So when I contacted you by email to ask about this problem, I wanted to know how you packaged it.

**Comment by crowforkotlin** [comment]
This problem is because jewel needs to use jbr runtime, and jpackage and jmod do not exist in jbr on Mac system, which leads to failure of packaging on Mac. So when I contacted you by email to ask about this problem, I wanted to know how you packaged. It is impossible to package on Mac (gradlew packageDmg), and then I introduced dev.hydraulic.conveyor:conveyor-control in my project. This supports fast packaging, but the effect is not very good.

**Comment by kaleidot725** [comment]
For some reason, when using jewel, dmg generation fails due to jbr. Also, we have decided to stop using jewel and jbr because the use of jbr has caused problems that complicate the build process.

**Comment by kaleidot725** [comment]
@crowforkotlin 
Thank you for your research. I have released a version as v1.3.0 that stops using JBR and Jewel. This issue has been resolved and is closed.

**Comment by crowforkotlin** [comment]
> @crowforkotlin Thank you for your research. I have released a version as v1.3.0 that stops using JBR and Jewel. This issue has been resolved and is closed.

You're welcome. My suggestion is that jewel can still be used, but you need to switch to the JBR environment and package it with the open source library I recommend or a cross-compiled library that jewel is currently requesting. Because it is not a simple matter for compose to modify the default statusbar, either use jewel or flatlaf, it will be very difficult to implement it yourself. And I think the jewel theme is very beautiful. In addition, I would like to ask you how the 1.2.0 Mac product dmg is packaged? Because I see that 1.2.0 has jewel
